### ISSUE TITLE
publicKeyHashToAddress() does not support BCH

### ISSUE THREAD

**Issue by akifuji** [yenom/BitcoinKit#141]
# Current behavior
In Helpers.swift, publicKeyHashToAddress() only support BTC
```
/// Version = 1 byte of 0 (zero); on the test network, this is 1 byte of 111
/// Key hash = Version concatenated with RIPEMD-160(SHA-256(public key))
/// Checksum = 1st 4 bytes of SHA-256(SHA-256(Key hash))
/// Bitcoin Address = Base58Encode(Key hash concatenated with Checksum)
func publicKeyHashToAddress(_ hash: Data) -> String {
    let checksum = Crypto.sha256sha256(hash).prefix(4)
    let address = Base58.encode(hash + checksum)
    return address
}
```

# Expected behavior
It should adapt to BCH too.

# Steps to reproduce
1. 
2. 
3. 

# Environment

- BitcoinKit: *?.?*
- Xcode Version: *?.? (????)*
- Swift Version: *?.?*

**Comment by usatie** [comment]
Oh, this code should be deprecated in near future.
This is currently only used for Legacy Address.

**Comment by usatie** [comment]
It's removed.
