### ISSUE TITLE
No swift files in "BitcoinKit.framework/Headers"

### ISSUE THREAD

**Issue by johnnytucker** [yenom/BitcoinKit#142]
# Current behavior
When I build "BitcoinKit/BitcoinKit.xcworkspace", it generates a Framework with no ".swift" files in "BitcoinKit.framework/Headers"

# Expected behavior
When I build "BitcoinKit/BitcoinKit.xcworkspace", I expect it to generate a Framework with ".swift" files in "BitcoinKit.framework/Headers"

# Fix
Adding swift files to the public headers section in Xcode (see attached)
![screen shot 2018-08-24 at 1 52 50 pm](https://user-images.githubusercontent.com/842751/44602566-91a8c780-a7a5-11e8-80ed-9a405fa2c515.png)

# Steps to reproduce
1.  git clone https://github.com/yenom/BitcoinKit.git
2.  open BitcoinKit/BitcoinKit.xcworkspace
3. Click 'Xcode->Product->Build'
4.  Notice that there's no ".swift" files in the generated "BitcoinKit.framework/Headers"

# Environment
- OS: macOS High Sierra 10.13.5 (17F77)
- BitcoinKit: Cloned on 8/24/2018 (BitcoinKit.podspec:  spec.version = '1.0.1')
- Xcode Version: 9.4.1 (9F2000)
- Swift Version: 4.1

**Comment by kishikawakatsumi** [comment]
Swift doesn't use header files. Instead, Swift uses `*.modulemap` and `*.swiftmodule` files. You don't need to copy the Swift files to Headers. @johnnytucker

**Comment by usatie** [comment]
@GitCash send 1000 bits to @kishikawakatsumi.

Thanks for answering to the question.

**Comment by GitCash** [comment]
Hey **kishikawakatsumi**, user **usatie** tipped you **1000 bits** in Bitcoin Cash ( ~ **$0.548** ).

*[Click here to claim it!](https://gitcash.io/claim/kishikawakatsumi)*

You can also add the "thumbs down" reaction to **usatie**'s comment above to prevent future tips.

**Comment by johnnytucker** [comment]
That's true.  For some reason it got me past my compile errors.
