### ISSUE TITLE
HDWallet.coinType is hard-code for BTC

### ISSUE THREAD

**Issue by johnnytucker** [yenom/BitcoinKit#143]
# Current behavior
HDWallet currently sets the coinType to either 0 or 1 (i.e. BTC or Testnet)

# Expected behavior
HDWallet sets the coinType based on SLIP-0044 https://github.com/satoshilabs/slips/blob/master/slip-0044.md

(e.g. coinType is 145 for BCH)

# Steps to reproduce
1. open BitcoinKit/Sources/BitcoinKit/Wallet/HDWallet.swift
2. Notice constructor sets the coinType to either 0 or 1 

# Environment
- OS: macOS High Sierra 10.13.5 (17F77)
- BitcoinKit: Cloned on 8/24/2018 (BitcoinKit.podspec: spec.version = '1.0.1')
- Xcode Version: 9.4.1 (9F2000)
- Swift Version: 4.1

**Comment by johnnytucker** [comment]
Here's a couple approaches for this coin type issue.

1) Add a coinType variable to the Network class hierarchy.

For example:

public class Network {
    public var bip44CoinType : Int { return 0 }
    ...
}


public class BCHMainnet: Mainnet {
    override var bip44CoinType : Int {
        return CoinTypes.BitcoinCash
    }
    ...
}

public final class HDWallet {
    private let coinType: CoinType

    public init(seed: Data, network: Network) {
        self.coinType = network.bip44CoinType
        ...
    } 
    ...
}

2) Add a CoinType argument to the HDWallet contructor.

For example:

public final class HDWallet {
    private let coinType: CoinType

    public init(seed: Data, network: Network, coinType: CoinType) {
        self.coinType = coinType
        ...
    } 
    ...
}

########
Also, I created the attached a CoinType.swift using the latest registered coin types from https://github.com/satoshilabs/slips/blob/master/slip-0044.md.  It could help even if you choose a different approach.

[CoinType.swift.txt](https://github.com/yenom/BitcoinKit/files/2334151/CoinType.swift.txt)

**Comment by johnnytucker** [comment]
The attached swift files contain all of the information in the registered coin types on https://github.com/satoshilabs/slips/blob/master/slip-0044.md.  

i.e.
```
public final class CoinTypes {
    let Bitcoin = CoinType(0, "BTC", "Bitcoin")
    let Testnet = CoinType(1, "", "Testnet (all coins)")
    let Litecoin = CoinType(2, "LTC", "Litecoin")
...
}
```

[CoinType-bip44-structures.zip](https://github.com/yenom/BitcoinKit/files/2334244/CoinType-bip44-structures.zip)

**Comment by usatie** [comment]
@johnnytucker Thank you, this will be included in the next release.
