### ISSUE TITLE
How to create a transaction with P2SH script UTXOs?（Segwit Transaction）

### ISSUE THREAD

**Issue by AlleniCode** [yenom/BitcoinKit#155]
<img width="736" alt="qq20180915-234156 2x" src="https://user-images.githubusercontent.com/8855341/45588040-f688b500-b940-11e8-9bff-9f228f6ada5a.png">

I get a UTXO with script type 'pay to script hash', how to create this transaction? Thx!

**Comment by akifuj** [comment]
`Script` class has `toP2SH`, which converts a script into 'pay to script hash' type.
Use this function and put it into scriptPubKey of a transaction.

**Comment by AlleniCode** [comment]
@akifuj Is there a demo or test for me?

**Comment by akifuj** [comment]
@AlleniCode 
This is an example for creating P2SH address of multisig.
The following codes show that `toP2SH` converts into 'pay to script hash' type.
```
let multisig = Script(publicKeys: [publicKeyA, publicKeyB, publicKeyC], signaturesRequired: 2)!
return multisig.toP2SH().standardAddress(network: .testnet)!
```

**Comment by AlleniCode** [comment]
@akifuj My question is not multisig, it's segwit, there are not publicKeyA, publicKeyB, publicKeyC, Just one publicKey and a script with type 'pay to script hash', I want spent this UTXO in my transaction.

**Comment by akifuj** [comment]
@AlleniCode 
Now I understand. 
Unfortunately, the library has not yet supported segwit.
We have already added [an issue](https://github.com/yenom/BitcoinKit/issues/92) about segwit, so please wait.

**Comment by DiwakarThapa** [comment]
testnet-seed.bitcoin.jonasschnelli.ch:18333 sending tx
testnet-seed.bitcoin.jonasschnelli.ch:18333 sending getblocks
testnet-seed.bitcoin.jonasschnelli.ch:18333 got inv with 1 item(s)
testnet-seed.bitcoin.jonasschnelli.ch:18333 sending getdata
testnet-seed.bitcoin.jonasschnelli.ch:18333 rejected tx code: 0x10 reason: bad-txns-inputs-duplicate, data:  

These error caused by segwit , Isn't it? . Those errors occurs in my console when I send transaction using testnetBTC.

**Comment by akifuji** [comment]
@DiwakarThapa 
If you try to use UTXOs which is generated with segwit, you will fail to create txs.

**Comment by akifuji** [comment]
@DiwakarThapa 
Currently, segwit is not supported. 
You need to write a raw-transaction for it.

**Comment by DiwakarThapa** [comment]
@akifuji  how to write raw transaction ? Do yo have references so that I can take help to write raw transaction ?
