### ISSUE TITLE
How to Create a new wallet with name and password

### ISSUE THREAD

**Issue by zhunye** [yenom/BitcoinKit#162]
# What problem does this feture solve?

# Describe what you've considered?

# Code sample / Spec

**Comment by akifuj** [comment]
Unfortunately, the library does not prepare such a function.
That function would be responsible for each application not the library.

**Comment by zhunye** [comment]
the example build failed
so I don't know how to create a new wallet 
I use oc,thanks

**Comment by zhunye** [comment]
> @zhunye
> Do you mean the function is like user registration?
> Unfortunately, the library does not prepare such a function.
> That function would be responsible for each application not the library.

the example build failed
so I don't know how to create a new wallet
I use oc,thanks

**Comment by zhunye** [comment]
> @akifuj 
> Do you mean the function is like user registration?
> Unfortunately, the library does not prepare such a function.
> That function would be responsible for each application not the library.

the example build failed
so I don't know how to create a new wallet
I use oc,thanks

**Comment by zhunye** [comment]
> @akifuj 
#import "ViewController.h"
#import <BitcoinKit/BitcoinKit-Swift.h>
@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    // Do any additional setup after loading the view, typically from a nib.
}

- (IBAction)create:(id)sender {
    //How do there,please
}
