### ISSUE TITLE
Failed to sync with BCH testnet

### ISSUE THREAD

**Issue by cuhte3** [yenom/BitcoinKit#165]
# Current behavior

Syncing with Bitcoin Cash testnet (BCHTestnet) is failed. 

Debugger output:

**start sync
testnet-seed-abc.bitcoinforks.org:18333 connecting
2018-09-20 17:17:50.590262+0300 Wallet[57043:20908774] [] nw_connection_get_connected_socket 1 Connection has no connected handler
2018-09-20 17:17:50.590664+0300 Wallet[57043:20908774] TCP Conn 0x60400016cb40 Failed : error 0:-65554 [-65554]
testnet-seed-abc.bitcoinforks.org:18333 socket error occurred
testnet-seed-abc.bitcoinforks.org:18333 disconnected**

# Expected behavior

Syncing with testnet-seed-abc.bitcoinforks.org or other node is successful 
# Steps to reproduce

1. Launch Wallet app (Examples folder)
2. Go to "Send" tab
3. Syncing with node or choosing other node to sync is failed

# Environment

- BitcoinKit: *1.0.2*
- Xcode Version: *9.4.1 (9F2000)*
- Swift Version: *4.1*

**Comment by akifuj** [comment]
@cuhte3 
SPV features are under construction and really unstable.
It is on our roadmap to modify it, so please wait.
