### ISSUE TITLE
objective-c can use this library?

### ISSUE THREAD

**Issue by zhunye** [yenom/BitcoinKit#166]
My project with oc,is it can use this library? if it can,how do
Thanks very much

**Comment by akifuj** [comment]
@zhunye 
BitcoinKit cannot be used in Object-C projects.
The main limitation is that most classes and types in the library are Swift-only.

This library is alternative for ObjC, although the maintenance has been stopped for 3 years.
https://github.com/oleganza/CoreBitcoin/tree/master/CoreBitcoin

**Comment by zhunye** [comment]
@akifuj
the CoreBitcoin how to use, eg:how to create a new wallet ?
if you have demo, please give me one.

**Comment by akifuj** [comment]
@zhunye 
Umm... I don't know sample code with CoreBitcoin.
I just searched and found this project, which might help you.
https://github.com/BitStore/BitStore-iOS

**Comment by zhunye** [comment]
@akifuj
thanks very much, I am a green hand 
I have 2 questions about BitcoinKit
1,let privateKey = PrivateKey （ network ： .testnet 
  let wallet = Wallet （ privateKey ：privateKey）
 then this wallet is btc or bch,and how to create them respectively
2,how to converter bch old address to new address bitcoincash:q.....
 becouse the README.md there:let cashaddrMain = try AddressFactory. create （ “ bitcoincash：qpjdpjrm5zvp2al5u4uzmp36t9m0ll7gd525rss978 ” ）,I don't find this function in BitcoinKit,and I don't
understand why input  a bch new address“ bitcoincash：qpjdpjrm5zvp2al5u4uzmp36t9m0ll7gd525rss978 ”  get a bch new address still
