### ISSUE TITLE
pod 'BitcoinKit'  ERROR Info

### ISSUE THREAD

**Issue by QA411** [yenom/BitcoinKit#175]
[!] /bin/bash -c 
set -e
sh setup/build_libraries.sh

++ dirname setup/build_libraries.sh
+ SCRIPT_DIR=setup
+ cd setup
+ sh build_secp256k1.sh
++ dirname build_secp256k1.sh
+ SCRIPT_DIR=.
++ mktemp -d
+ TDIR=/var/folders/yr/vb_kws793p9gtx0b358sd8640000gp/T/tmp.rYwzJed1
+ trap '{ cd - ; rm -rf /var/folders/yr/vb_kws793p9gtx0b358sd8640000gp/T/tmp.rYwzJed1; exit 255; }' SIGINT
+ cd /var/folders/yr/vb_kws793p9gtx0b358sd8640000gp/T/tmp.rYwzJed1
+ git clone https://github.com/bitcoin-core/secp256k1.git src
Cloning into 'src'...
++ pwd
+ CURRENTPATH=/var/folders/yr/vb_kws793p9gtx0b358sd8640000gp/T/tmp.rYwzJed1
+ TARGETDIR_IPHONEOS=/var/folders/yr/vb_kws793p9gtx0b358sd8640000gp/T/tmp.rYwzJed1/.build/iphoneos
+ mkdir -p /var/folders/yr/vb_kws793p9gtx0b358sd8640000gp/T/tmp.rYwzJed1/.build/iphoneos
+ TARGETDIR_SIMULATOR=/var/folders/yr/vb_kws793p9gtx0b358sd8640000gp/T/tmp.rYwzJed1/.build/iphonesimulator
+ mkdir -p /var/folders/yr/vb_kws793p9gtx0b358sd8640000gp/T/tmp.rYwzJed1/.build/iphonesimulator
+ cd src
+ ./autogen.sh
./autogen.sh: line 3: autoreconf: command not found

**Comment by akifuj** [comment]
Hi @QA411 
Did you check #52 ? This might help you.
