### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by QA411** [yenom/BitcoinKit#183]
eg: let unspentOutpoint = TransactionOutPoint(hash: Data(hex: "e28c2b955293159898e34c6840d99bf4d390e2ee1c6f606939f18ee1e2000d05")!, index: 2)

how to get hex and index? e28c2b955293159898e34c6840d99bf4d390e2ee1c6f606939f18ee1e2000d05

**Comment by usatie** [comment]
```
let hex = unspentOutpoint.hash.hex
let index = unspentOutpoint.index
```

<img width="741" alt="screen shot 2018-11-21 at 0 55 34" src="https://user-images.githubusercontent.com/7609060/48785515-2e88eb80-ed28-11e8-8733-3d937e7aa0fa.png">

**Comment by QA411** [comment]
oh,brother I'm sorry. I want get e28c2b955293159898e34c6840d99bf4d390e2ee1c6f606939f18ee1e2000d05 and 2 .
