### ISSUE TITLE
swift4.1 error

### ISSUE THREAD

**Issue by h-js** [yenom/BitcoinKit#49]
public static func buildPublicKeyHashOut(pubKeyHash: Data) -> Data {
        return Data() + OP_DUP + OP_HASH160 + OP_0 + pubKeyHash + OP_EQUALVERIFY + OP_CHECKSIG
    }

**Comment by Jax1993** [comment]
I fixed by:

    public static func buildPublicKeyHashOut(pubKeyHash: Data) -> Data {
        var tmp = Data() + OP_DUP + OP_HASH160 + OP_0 + pubKeyHash + OP_EQUALVERIFY
        return tmp + OP_CHECKSIG
    }

**Comment by J-Liu** [comment]
@Jax1993 make a pull request:)

**Comment by SunLn** [comment]
https://github.com/kishikawakatsumi/BitcoinKit/pull/67

**Comment by usatie** [comment]
This should be fixed.
Thanks for reporting the issue!

We already fixed in [yenom/BitcoinCashKit](https://github.com/yenom/BitcoinCashKit), and it is now on PR.
