### ISSUE TITLE
Problem with generating raw transaction. 

### ISSUE THREAD

**Issue by OleksiiShulzhenko** [yenom/BitcoinKit#57]
'TransactionOutput' initializer is inaccessible due to 'internal' protection level
Or am I doing something wrong? Is there an example?

**Comment by cnsuer** [comment]
How to generating raw transaction?  Plsese tell me ....... Very Thank You...

**Comment by kostilal** [comment]
Hi @OleksiiShulzhenko , do you fix the problem?

**Comment by OleksiiShulzhenko** [comment]
@kostilal ,i made my own changes to the library.

**Comment by kostilal** [comment]
@OleksiiShulzhenko, could you please give me your skype or telegram?

**Comment by OleksiiShulzhenko** [comment]
@shulalex

2018-07-04 12:42 GMT+03:00 Ilya Kostyukevich <notifications@github.com>:

**Comment by usatie** [comment]
Thanks for creating the issue!
We fixed it on our PR.
