### ISSUE TITLE
Cannot import BitcoinKit for Sample.playground

### ISSUE THREAD

**Issue by akifuj** [yenom/BitcoinKit#79]
# Current behavior
I cannot import BitcoinKit when running `Sample.playground`.
How does it solve this problem?

# Environment

- BitcoinKit: 1.0.1
- Xcode Version: 9.4.1
- Swift Version: 4.1.2

**Comment by usatie** [comment]
The `No such module "BitcoinKit"` error is thrown when you are selecting "Generic iOS Device" as a build target. 
Please select any of iOS simulators.
